export const locations = ['Chennai', 'Coimbatore', 'Bengaluru', 'Madurai'];
export const statuses = ['Open', 'In Progress', 'Waiting for Parts', 'Completed', 'Closed'];
const models = ['iPhone 15 Pro', 'iPhone 15', 'iPhone 14', 'iPhone 13', 'MacBook Pro 14', 'MacBook Air M2', 'iPad Pro 12.9', 'iPad Air'];
const people = ['Arun Kumar', 'Meera Iyer', 'Ravi Shankar', 'Nisha Rao', 'Karthik S'];
export const demoDevices = Array.from({ length: 20 }, (_, index) => ({ _id: `device-${index + 1}`, assetId: `AST-${String(index + 1).padStart(3, '0')}`, serialNumber: `APL-DEMO-${String(index + 1).padStart(4, '0')}`, deviceType: models[index % models.length].startsWith('iPhone') ? 'iPhone' : models[index % models.length].startsWith('iPad') ? 'iPad' : 'MacBook', model: models[index % models.length], employeeName: people[index % people.length], employeeId: `EMP-${1001 + index}`, department: ['IT', 'Finance', 'Operations', 'Sales'][index % 4], location: locations[index % 4], purchaseDate: '2023-04-12', warrantyStatus: index % 5 === 0 ? 'Expired' : index % 4 === 0 ? 'Expiring Soon' : 'Active', warrantyExpiry: `202${6 + (index % 2)}-${String((index % 9) + 1).padStart(2, '0')}-20`, amcStatus: index % 4 === 1 ? 'Expired' : index % 3 === 0 ? 'Expiring Soon' : 'Active', amcExpiry: '2027-08-15', deviceStatus: index % 6 === 0 ? 'Under Service' : 'In Use', lastServiceDate: '2025-06-04' }));
export const demoTickets = Array.from({ length: 12 }, (_, index) => ({ _id: `ticket-${index + 1}`, ticketId: `TKT-2026-${String(index + 1).padStart(3, '0')}`, deviceId: demoDevices[index % demoDevices.length], issueType: ['Battery', 'Screen / Display', 'Charging', 'Performance', 'Keyboard'][index % 5], description: 'Demo service issue requiring technician inspection.', location: locations[index % 4], priority: ['Low', 'Medium', 'High', 'Critical'][index % 4], status: statuses[index % statuses.length], assignedEngineer: index % 3 === 0 ? 'Unassigned' : ['Vikram S', 'Priya Menon'][index % 2], expectedTAT: `${1 + (index % 4)} business days`, createdAt: `2026-08-${String(index + 1).padStart(2, '0')}`, images: [] }));
export const volumeData = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'].map((month, index) => ({ month, tickets: [4, 6, 5, 8, 7, 10, 8, 12, 9][index] }));
export const locationData = locations.map((name, index) => ({ name, value: [7, 5, 5, 3][index] }));
export const demoProfile = { name: 'Arun Kumar', email: 'customer@demo.com', company: 'Demo Technologies Pvt Ltd', phone: '+91 90000 00000', primaryLocation: 'Chennai', numberOfDevices: 20 };
