import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Star } from 'lucide-react';
import { Shell, PageTitle, Badge } from './components';
import { getTicket, submitReview } from './api';

export function ReviewPage() {
  const { ticketId } = useParams();
  const [data, setData] = useState(null); const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [complete, setComplete] = useState(false);
  useEffect(() => { getTicket(ticketId).then(setData).catch(error => setError(error.message || 'Unable to load this service request.')); }, [ticketId]);
  const submit = async event => { event.preventDefault(); if (!rating || !comment.trim()) { setError('Choose a rating and tell us about your experience.'); return; } try { setBusy(true); setError(''); await submitReview({ ticketId, rating, comment }); setComplete(true); } catch (submitError) { setError(submitError.message || 'Unable to submit your review.'); if (/already been reviewed/i.test(submitError.message)) setComplete(true); } finally { setBusy(false); } };
  if (!data) return <Shell title="Rate our service"><div className="loading">{error || 'Loading service request...'}</div></Shell>;
  const { ticket, reviewEligible, reviewSubmitted } = data;
  const rated = complete || reviewSubmitted;
  return <Shell title="Rate our service"><PageTitle title="Rate Your Service" description="Your feedback helps the service team improve." /><section className="panel review-form-panel"><span className="kicker">Service request</span><h2>{ticket.ticketId}</h2><div className="info-row"><span>Device</span><strong>{ticket.deviceId?.model || 'Device'}</strong></div><div className="info-row"><span>Service Centre</span><strong>{ticket.serviceCentreId?.name || ticket.location || 'iPlanet Service Centre'}</strong></div>{rated ? <div className="success-state"><h3>Thank you for your feedback.</h3><p>This service request has already been reviewed.</p><Link className="button primary" to={`/corporate/service-requests/${ticketId}`}>Back to Service Request</Link></div> : !reviewEligible ? <div className="empty"><p>This service request is not ready for a review yet.</p><Link className="button secondary" to={`/corporate/service-requests/${ticketId}`}>Back to Service Request</Link></div> : <form onSubmit={submit}><fieldset className="rating-fieldset"><legend>How was your service experience?</legend><div className="star-rating">{[1, 2, 3, 4, 5].map(value => <button key={value} type="button" className={value <= rating ? 'selected' : ''} aria-label={`${value} star${value === 1 ? '' : 's'}`} aria-pressed={rating === value} onClick={() => setRating(value)} onKeyDown={event => { if (event.key === 'ArrowRight') setRating(Math.min(5, value + 1)); if (event.key === 'ArrowLeft') setRating(Math.max(1, value - 1)); }}><Star size={30} fill={value <= rating ? 'currentColor' : 'none'} /></button>)}</div></fieldset><label>Tell us about your experience<textarea required maxLength="2000" value={comment} onChange={event => setComment(event.target.value)} placeholder="Share your feedback about the service." /></label>{error && <p className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Submitting...' : 'Submit Review'}</button></form>}</section></Shell>;
}
